// Code generated by "stringer -type ObjectType"; DO NOT EDIT.

package object

import "strconv"

const _ObjectType_name = "INTEGERBOOLEANNULLERRORFUNCTIONSTRINGRETURN_VALUE"

var _ObjectType_index = [...]uint8{0, 7, 14, 18, 23, 31, 37, 49}

func (i ObjectType) String() string {
	i -= 1
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
